export type Genre = "r&b"| "pop"| "rock"| "indie"| "folk"| "jazz"

export interface Discovery {
  type: Genre;
  name: string;
  album: string;
  year: string;
  favTrack: string;
  rating: number;
  image: string;
}

export const data: Discovery[] = [
  {
    type: "r&b",
    name: "Khamari",
    album: "A Brief Nirvana",
    year: "2023",
    favTrack: "Doctor, My Eyes",
    rating: 10,
    image: 'khamari-album-cover.jpg',
  },
  {
    type: "pop",
    name: "Olivia Dean",
    album: "Messy",
    year: "2023",
    favTrack: "Dive",
    rating: 10,
    image: 'olivia-dean-album-cover.avif',
  },
  {
    type: "rock",
    name: "Maggie Lindemann",
    album: "HEADSPLIT",
    year: "2024",
    favTrack: "hostage",
    rating: 10,
    image: 'maggie-lindemann-album-cover.jpg',
  },
  {
    type: "indie",
    name: "The Fratellis",
    album: "In Our Own Sweet Time",
    year: "2018",
    favTrack: "Starcrossed Lovers",
    rating: 10,
    image: 'the-fratellis-album-cover.jpg',
  },
  {
    type: "folk",
    name: "Vance Joy",
    album: "Dream Your Life Away",
    year: "2014",
    favTrack: "Riptide",
    rating: 10,
    image: 'vance-joy-album-cover.avif',
  },
  {
    type: "jazz",
    name: "Ella Fitzgerald",
    album: "Get Happy!",
    year: "1959",
    favTrack: "Blue Skies",
    rating: 10,
    image: 'ella-fitzgerald-album-cover.jpg',
  },
  {
    type: "r&b",
    name: "GIVEON",
    album: "BELOVED",
    year: "2025",
    favTrack: "TWENTIES",
    rating: 10,
    image: 'giveon-album-cover.jpg',
  },
  {
    type: "folk",
    name: "Nick Drake",
    album: "Pink Moon",
    year: "1972",
    favTrack: "Pink Moon",
    rating: 10,
    image: 'nick-drake-album-cover-2.avif',
  },
  {
    type: "folk",
    name: "Nick Drake",
    album: "Bryter Layter",
    year: "1970",
    favTrack: "Northern Sky",
    rating: 10,
    image: 'nick-drake-album-cover.jpg',
  },
  {
    type: "pop",
    name: "Demi Lovato",
    album: "It's Not That Deep",
    year: "2025",
    favTrack: "Here All Night",
    rating: 10,
    image: 'demi-lovato-album-cover.avif',
  },
  {
    type: "jazz",
    name: "Louis Armstrong",
    album: "What A Wonderful World",
    year: "1968",
    favTrack: "What A Wonderful World",
    rating: 10,
    image: 'louis-armstrong-album-cover.jpg',
  },
  {
    type: "indie",
    name: "Joanna Newsom",
    album: "Ys",
    year: "1968",
    favTrack: "Sawdust and Diamonds",
    rating: 10,
    image: 'joanna-newson-album-cover.jpg',
  },
  {
    type: "rock",
    name: "The Pretty Reckless",
    album: "Light Me Up",
    year: "2010",
    favTrack: "Make Me Wanna Die",
    rating: 10,
    image: 'the-pretty-reckless-album-cover.jpg',
  },
  {
    type: "pop",
    name: "Lady Gaga",
    album: "MAYHEM",
    year: "2025",
    favTrack: "Abracadabra",
    rating: 10,
    image: 'lady-gaga-album-cover.avif',
  },
    {
    type: "rock",
    name: "All Time Low",
    album: "Nothing Personal",
    year: "2009",
    favTrack: "Break Your Little Heart",
    rating: 10,
    image: 'all-time-low-album-cover.jpg',
  },
  {
    type: "rock",
    name: "Parkway Drive",
    album: "Darker Still",
    year: "2022",
    favTrack: "Glitch",
    rating: 10,
    image: 'parkway-drive-album-cover.jpg',
  },
  {
    type: "folk",
    name: "Taylor Swift",
    album: "Folklore",
    year: "2020",
    favTrack: "cardigan",
    rating: 10,
    image: 'taylor-swift-album-cover.avif',
  },
  {
    type: "indie",
    name: "Jake Bugg",
    album: "Hearts That Strain",
    year: "2017",
    favTrack: "Waiting",
    rating: 10,
    image: 'jake-bugg-album-cover.jpg',
  },
    {
    type: "jazz",
    name: "Billie Holiday",
    album: "Billie Holiday",
    year: "1952",
    favTrack: "I'll Be Seeing You",
    rating: 10,
    image: 'billie-holiday-album-cover.jpg',
  },
];

